# -*- coding: utf-8 -*-
"""SeQR_model.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sHvJx9PzLgHtgYv667_MIgxfW5E2z1iI
"""

# pip install pipeline


"""### ealvaradob/bert-finetuned-phishing"""

# Use a pipeline as a high-level helper
import pandas as pd
import os
from transformers import pipeline

pipe = pipeline("text-classification", model="ealvaradob/bert-finetuned-phishing")

from google.colab import drive
drive.mount('/content/drive')

# Google Drive에 저장된 파일 경로
ROOT_DIR = "/content/drive/MyDrive/졸업프로젝트팀/인지대 공모전/data"

# 텍스트 파일을 DataFrame으로 로드
df = pd.read_csv(os.path.join(ROOT_DIR, 'combined_phishing_data.txt'), header=None, delimiter='\t', names=['label', 'URL'])

# 'label' 컬럼 이름을 '실제 피싱 여부'로 변경
df.rename(columns={'label': 'Actual'}, inplace=True)

# URL 리스트 생성
urls = df['URL'].tolist()

# Hugging Face 모델로 예측 수행
results = pipe(urls)

# 예측된 'label' (phishing 여부)을 새로운 컬럼에 추가
df['Predicted Label'] = [result['label'] for result in results]

# 예측 결과를 DataFrame에 추가 ('score'는 피싱일 확률)
df['Prediction Score'] = [f"{result['score'] * 100:.2f} %" for result in results]

# DataFrame을 CSV로 저장
df.to_csv(os.path.join(ROOT_DIR, 'combined_phishing_data_with_results_bert.csv'), index=False)

# 텍스트 파일을 DataFrame으로 로드
df = pd.read_csv(os.path.join(ROOT_DIR, 'combined_benign_data.txt'), header=None, delimiter='\t', names=['label', 'URL'])

# 'label' 컬럼 이름을 '실제 피싱 여부'로 변경
df.rename(columns={'label': 'Actual'}, inplace=True)

# URL 리스트 생성
urls = df['URL'].tolist()

# Hugging Face 모델로 예측 수행
results = pipe(urls)

# 예측된 'label' (phishing 여부)을 새로운 컬럼에 추가
df['Predicted Label'] = [result['label'] for result in results]

# 예측 결과를 DataFrame에 추가 ('score'는 피싱일 확률)
df['Prediction Score'] = [f"{result['score'] * 100:.2f} %" for result in results]

# DataFrame을 CSV로 저장
df.to_csv(os.path.join(ROOT_DIR, 'combined_benign_data_with_results_bert.csv'), index=False)

